import { ToolDefinition } from "./types";

export const ALL_TOOLS: ToolDefinition[] = [
  // 1. AI CATEGORY
  {
    id: "ai-assistant",
    name: "Smart AI Chat Assistant",
    description: "Multi-model conversation helper with history, export, regeneration, and copy support.",
    icon: "MessageSquareText",
    category: "AI",
    usageCount: 201100,
    trending: true,
  },
  {
    id: "ai-writer",
    name: "AI Article & Essay Writer",
    description: "Generate high-quality blog posts, essays, marketing copies, and outlines with full SEO optimization.",
    icon: "Sparkles",
    category: "AI",
    usageCount: 142050,
  },
  {
    id: "ai-summarizer",
    name: "AI Document Summarizer",
    description: "Summarize long-form text, research papers, or contract documents into key points instantly.",
    icon: "FileText",
    category: "AI",
    usageCount: 89400,
  },
  {
    id: "ai-translator",
    name: "AI Neural Translator",
    description: "High-precision translator supporting multiple languages with auto formatting and dialect detection.",
    icon: "Languages",
    category: "AI",
    usageCount: 76500,
    new: true,
  },
  {
    id: "ai-grammar",
    name: "AI Grammar & Style Coach",
    description: "Fix grammar mistakes, correct phrasing, and elevate sentence structure to native professional writing.",
    icon: "SpellCheck",
    category: "AI",
    usageCount: 65400,
  },
  {
    id: "ai-humanizer",
    name: "AI Humanizer Bypass Engine",
    description: "Rewrite generic machine-generated AI texts into high-quality casual, formal, or highly conversational natural text.",
    icon: "Workflow",
    category: "AI",
    usageCount: 54900,
    new: true,
  },
  {
    id: "ai-email",
    name: "AI Professional Email Writer",
    description: "Generate pitch emails, replies, or professional followups with perfect dynamic tones.",
    icon: "Mail",
    category: "AI",
    usageCount: 73200,
  },
  {
    id: "ai-social",
    name: "AI Social Media Captain",
    description: "Generate creative captions, TikTok titles, YouTube hooks, and optimized keyword hashtags.",
    icon: "Compass",
    category: "AI",
    usageCount: 88100,
  },
  {
    id: "ai-image-gen",
    name: "AI Text-to-Image Generator",
    description: "Create stunning high-definition visual assets, vectors, and digital artwork with prompt details.",
    icon: "Palette",
    category: "AI",
    usageCount: 119500,
    trending: true,
  },
  {
    id: "ai-image-enhance",
    name: "AI Image Upscaler & Enhancer",
    description: "Restore grainy, blurry, or low-resolution images to crystal-clear 4K quality using AI scaling.",
    icon: "Eye",
    category: "AI",
    usageCount: 64200,
  },
  {
    id: "ai-image-bg-remover",
    name: "AI Background Remover",
    description: "Instantly detect subjects and strip backgrounds cleanly for transparent PNG cutout outputs.",
    icon: "Scissors",
    category: "AI",
    usageCount: 92400,
  },
  {
    id: "ai-image-obj-remover",
    name: "AI Smart Object Eraser",
    description: "Erase unneeded elements, photobombers, or texts from snapshots with AI fill-in algorithms.",
    icon: "Trash2",
    category: "AI",
    usageCount: 41200,
  },

  // 2. PDF CATEGORY
  {
    id: "pdf-to-word",
    name: "PDF to Word Converter",
    description: "Extract documents to editable Microsoft Word files while keeping alignment and original layout.",
    icon: "FileText",
    category: "PDF",
    usageCount: 124500,
    trending: true,
  },
  {
    id: "pdf-to-excel",
    name: "PDF to Excel Converter",
    description: "Analyze, scrape, and export grid tables from PDFs into fully functional spreadsheets.",
    icon: "Files",
    category: "PDF",
    usageCount: 56900,
  },
  {
    id: "pdf-to-ppt",
    name: "PDF to PowerPoint",
    description: "Turn standard pages or visual reports into PowerPoint slide presentations.",
    icon: "Palette",
    category: "PDF",
    usageCount: 43500,
  },
  {
    id: "word-to-pdf",
    name: "Word Document to PDF",
    description: "Convert DOCX files into beautiful read-only PDFs with crisp universal font rendering.",
    icon: "FilePlus2",
    category: "PDF",
    usageCount: 78100,
  },
  {
    id: "excel-to-pdf",
    name: "Excel Sheet to PDF",
    description: "Print and align large tabular spreadsheets cleanly into structured, page-broken PDFs.",
    icon: "FileText",
    category: "PDF",
    usageCount: 39100,
  },
  {
    id: "ppt-to-pdf",
    name: "PowerPoint to PDF Converter",
    description: "Lock and convert presentations to PDF format for secure, unmodifiable public sharing.",
    icon: "FilePlus2",
    category: "PDF",
    usageCount: 45200,
  },
  {
    id: "image-to-pdf",
    name: "JPG / PNG to PDF",
    description: "Pack multiple visual photos, scanned receipts, or PNGs into a single combined PDF document.",
    icon: "FilePlus2",
    category: "PDF",
    usageCount: 91400,
  },
  {
    id: "pdf-merge",
    name: "Merge PDF Documents",
    description: "Combine multiple separate document files into one master PDF in any custom sequence.",
    icon: "FilePlus2",
    category: "PDF",
    usageCount: 154600,
    trending: true,
  },
  {
    id: "pdf-split",
    name: "Split PDF Pages",
    description: "Extract individual sheets or define custom page ranges to split documents into smaller files.",
    icon: "Scissors",
    category: "PDF",
    usageCount: 67200,
  },
  {
    id: "pdf-compress",
    name: "Compress PDF Size",
    description: "Shrink heavy PDF mb size for fast email attachments without blurring core texts.",
    icon: "Maximize2",
    category: "PDF",
    usageCount: 112100,
  },
  {
    id: "pdf-rotate",
    name: "Rotate PDF Pages",
    description: "Correct sideways pages or vertical flips instantly on any imported PDF layout.",
    icon: "Workflow",
    category: "PDF",
    usageCount: 32400,
  },
  {
    id: "pdf-delete-pages",
    name: "Delete Selected Pages",
    description: "Prune, clean, or cut unwanted sheets out of heavy corporate document briefs.",
    icon: "Trash2",
    category: "PDF",
    usageCount: 48900,
  },
  {
    id: "pdf-extract-pages",
    name: "Extract Specific Pages",
    description: "Select, duplicate, and save specific pages as an independent standalone PDF file.",
    icon: "FileText",
    category: "PDF",
    usageCount: 52100,
  },
  {
    id: "pdf-protect",
    name: "Protect PDF Password",
    description: "Add unbreakable AES military password encryption to protect critical document papers.",
    icon: "Lock",
    category: "PDF",
    usageCount: 42300,
  },
  {
    id: "pdf-unlock",
    name: "Unlock PDF Password",
    description: "Remove security passwords from owned papers to enable seamless sharing and prints.",
    icon: "Key",
    category: "PDF",
    usageCount: 65100,
  },
  {
    id: "pdf-watermark",
    name: "PDF Watermark Stamper",
    description: "Overlay customizable copyright text or company logo watermarks onto document grids.",
    icon: "Fingerprint",
    category: "PDF",
    usageCount: 29500,
  },
  {
    id: "pdf-signature",
    name: "PDF Digital Signer",
    description: "Draw, upload, or type safe electronic signatures directly onto formal legal contracts.",
    icon: "SpellCheck",
    category: "PDF",
    usageCount: 78400,
    new: true,
  },

  // 3. IMAGE CATEGORY
  {
    id: "image-converter",
    name: "Universal Image Converter",
    description: "Fast multi-format conversion between JPG, PNG, WEBP, AVIF, GIF, or SVG formats.",
    icon: "Workflow",
    category: "Image",
    usageCount: 134200,
    trending: true,
  },
  {
    id: "image-resize",
    name: "Aesthetic Image Resizer",
    description: "Set custom width and height, lock aspect ratios, or use responsive presets.",
    icon: "Maximize2",
    category: "Image",
    usageCount: 184500,
  },
  {
    id: "image-crop",
    name: "Smart Preset Image Cropper",
    description: "Trim borders or fit to standard aspect ratios (16:9, 4:3, 1:1 square) cleanly.",
    icon: "Scissors",
    category: "Image",
    usageCount: 95400,
  },
  {
    id: "image-compress",
    name: "Optimize & Compress Image",
    description: "Control quality factor compression ratios to minimize web image payloads.",
    icon: "Maximize2",
    category: "Image",
    usageCount: 142100,
  },
  {
    id: "image-rotate",
    name: "Rotate & Flip Visuals",
    description: "Mirror, turn, or flip visual images vertically or horizontally.",
    icon: "Workflow",
    category: "Image",
    usageCount: 38100,
  },
  {
    id: "image-watermark",
    name: "Aesthetic Image Watermarker",
    description: "Stamp customized watermark labels or logo overlays onto digital photos.",
    icon: "Fingerprint",
    category: "Image",
    usageCount: 46200,
  },

  // 4. VIDEO CATEGORY
  {
    id: "video-converter",
    name: "Fast Video Converter",
    description: "Transcode video files (MP4, MOV, WEBM) with custom target codecs, resolution, and quality scaling.",
    icon: "Video",
    category: "Video",
    usageCount: 65400,
  },
  {
    id: "video-trim",
    name: "Precision Video Trimmer",
    description: "Cut and trim unwanted parts, timelines, or clips from video files.",
    icon: "Scissors",
    category: "Video",
    usageCount: 48900,
  },
  {
    id: "video-merge",
    name: "Simple Video Joiner",
    description: "Stitch together multiple film reels, videos, or clips into one continuous movie.",
    icon: "FilePlus2",
    category: "Video",
    usageCount: 32100,
  },
  {
    id: "video-compress",
    name: "Heavy Video Compressor",
    description: "Optimize bitrate and compress MP4 sizes for Discord, email, or Slack messaging.",
    icon: "Maximize2",
    category: "Video",
    usageCount: 71200,
  },
  {
    id: "video-extract-audio",
    name: "Audio Extractor (MP3)",
    description: "Extract pure high-quality background audio tracks from any movie as an MP3 file.",
    icon: "Music",
    category: "Video",
    usageCount: 52400,
  },
  {
    id: "video-create-gif",
    name: "High-Fidelity GIF Maker",
    description: "Convert custom video ranges or loops into optimized custom web GIF files.",
    icon: "Palette",
    category: "Video",
    usageCount: 41200,
  },

  // 5. AUDIO CATEGORY
  {
    id: "audio-converter",
    name: "Universal Audio Converter",
    description: "Convert and export files to MP3, WAV, AAC, or OGG extensions easily.",
    icon: "Music",
    category: "Audio",
    usageCount: 54200,
  },
  {
    id: "audio-compress",
    name: "Audio Bitrate Compressor",
    description: "Reduce audio file sizes by lowering constant or variable audio bitrates.",
    icon: "Maximize2",
    category: "Audio",
    usageCount: 29800,
  },
  {
    id: "audio-cutter",
    name: "MP3 Ringtone Cutter",
    description: "Select specific minutes or seconds to cut short audio files or alarm melodies.",
    icon: "Scissors",
    category: "Audio",
    usageCount: 61400,
  },
  {
    id: "audio-merger",
    name: "Multitrack Audio Merger",
    description: "Blend or concatenate multiple speech or track files into one master timeline.",
    icon: "FilePlus2",
    category: "Audio",
    usageCount: 22100,
  },
  {
    id: "audio-voice-recorder",
    name: "Web Voice Recorder",
    description: "Record crisp speech from your microphone directly and download it as a WAV file.",
    icon: "Mic",
    category: "Audio",
    usageCount: 75200,
    new: true,
  },
  {
    id: "audio-tts",
    name: "Text to Speech Synthesizer",
    description: "Convert written textual instructions into fully natural spoken voices.",
    icon: "Volume2",
    category: "Audio",
    usageCount: 94300,
    trending: true,
  },
  {
    id: "audio-stt",
    name: "Speech to Text transcriber",
    description: "Upload audio and convert spoken voice into editable structural paragraphs.",
    icon: "Mic2",
    category: "Audio",
    usageCount: 41200,
  },
  {
    id: "audio-voice-changer",
    name: "Dynamic Voice Changer",
    description: "Apply fun speech effects (Echo, Robot, Chipmunk, Deep Pitch) to audio.",
    icon: "Workflow",
    category: "Audio",
    usageCount: 33400,
  },

  // 6. TEMP MAIL CATEGORY
  {
    id: "temp-mail",
    name: "Instant Temporary Email",
    description: "Protect your personal inbox. Generate random temporary emails with active inboxes for verifications.",
    icon: "Mail",
    category: "Temp Mail",
    usageCount: 182400,
    trending: true,
  },

  // 7. URL CATEGORY
  {
    id: "url-shortener",
    name: "Premium URL Shortener",
    description: "Create quick redirects with customizable aliases, QR codes, password protection, and live trackers.",
    icon: "Link",
    category: "URL",
    usageCount: 154600,
    trending: true,
  },
  {
    id: "bio-link-builder",
    name: "Bio-Link Social Landing Page",
    description: "Assemble a responsive social landing profile, aggregate links, customize layouts and backgrounds.",
    icon: "Smartphone",
    category: "URL",
    usageCount: 62400,
    new: true,
  },

  // 8. QR CODE CATEGORY
  {
    id: "qr-generator",
    name: "Dynamic QR Code Generator",
    description: "Instantly create customized QR codes for URLs, WiFi configurations, phone numbers, locations, and texts.",
    icon: "QrCode",
    category: "QR Code",
    usageCount: 95300,
    trending: true,
  },
  {
    id: "qr-scanner",
    name: "Live Image & Camera Scanner",
    description: "Scan QR codes instantly by uploading visual files or starting your camera.",
    icon: "Scan",
    category: "QR Code",
    usageCount: 43200,
  },

  // 9. FILE CATEGORY
  {
    id: "file-sharing",
    name: "Secure Temp File Locker",
    description: "Upload, store, and share visual or zipped files with customizable expiration timers.",
    icon: "Upload",
    category: "File",
    usageCount: 84300,
  },
  {
    id: "file-splitter",
    name: "Gigabyte File Splitter",
    description: "Split exceptionally large files into smaller parts for simplified downloads or transfers.",
    icon: "Scissors",
    category: "File",
    usageCount: 19500,
  },
  {
    id: "file-merger",
    name: "Binary File Assembler",
    description: "Merge fragmented file components or blocks back into a single original file.",
    icon: "FilePlus2",
    category: "File",
    usageCount: 15400,
  },
  {
    id: "zip-creator",
    name: "Web ZIP Archive Creator",
    description: "Compress directories or multiple document files into single downloadable zip folders.",
    icon: "Zip",
    category: "File",
    usageCount: 65100,
  },
  {
    id: "zip-extractor",
    name: "ZIP Unarchiver Utility",
    description: "Browse, unpack, and view files from zipped folders directly in your browser.",
    icon: "FolderPlus",
    category: "File",
    usageCount: 49800,
  },
  {
    id: "file-batch-rename",
    name: "Batch Filename Renamer",
    description: "Rename lists of files instantly using customizable prefixes, suffixes, or regex find and replace.",
    icon: "Workflow",
    category: "File",
    usageCount: 22100,
  },
  {
    id: "file-duplicate-finder",
    name: "Duplicate File Sweeper",
    description: "Scan batches of assets and find identical duplicates based on name or binary size.",
    icon: "Trash2",
    category: "File",
    usageCount: 18400,
  },

  // 10. TEXT CATEGORY
  {
    id: "text-counter",
    name: "Word & Character Counter",
    description: "Analyze paragraphs instantly. Count words, letters, lines, spaces, read times, and unique words.",
    icon: "FileText",
    category: "Text",
    usageCount: 112400,
  },
  {
    id: "text-case-converter",
    name: "Case Style Converter",
    description: "Instantly switch string casings (UPPERCASE, lowercase, Title Case, camelCase, snake_case).",
    icon: "Workflow",
    category: "Text",
    usageCount: 84300,
  },
  {
    id: "text-cleaner",
    name: "Aesthetic Text Sanitizer",
    description: "Clean up unneeded quotes, replace tabs with spaces, remove emoji scripts, or trim spacing.",
    icon: "Trash2",
    category: "Text",
    usageCount: 45200,
  },
  {
    id: "text-remove-lines",
    name: "Duplicate & Empty Line Filter",
    description: "Strip duplicates or blank line spaces from your plain lists or datasets instantly.",
    icon: "Scissors",
    category: "Text",
    usageCount: 39500,
  },
  {
    id: "text-diff-checker",
    name: "Diff Difference Checker",
    description: "Compare two paragraphs side by side to highlight additions, edits, or removals.",
    icon: "ShieldAlert",
    category: "Text",
    usageCount: 58400,
  },
  {
    id: "text-lorem-generator",
    name: "Lorem Ipsum & Filler Text",
    description: "Generate mock placeholder paragraphs, sentences, words, or lists for UI designs.",
    icon: "Palette",
    category: "Text",
    usageCount: 62500,
  },
  {
    id: "text-password-generator",
    name: "Aesthetic Password Generator",
    description: "Produce secure, high-entropy random passwords with customized numbers, caps, or signs.",
    icon: "Lock",
    category: "Text",
    usageCount: 91400,
  },

  // 11. DEVELOPER CATEGORY
  {
    id: "json-formatter",
    name: "JSON Syntax Formatter",
    description: "Validate, format, prettify, or minify raw JSON string payloads.",
    icon: "Braces",
    category: "Developer",
    usageCount: 125800,
    trending: true,
  },
  {
    id: "xml-yaml-formatter",
    name: "XML / YAML Formatter",
    description: "Prettify nested XML sheets or indentation-strict YAML files in one click.",
    icon: "Code",
    category: "Developer",
    usageCount: 43100,
  },
  {
    id: "code-formatter",
    name: "HTML / CSS / JS / SQL Formatter",
    description: "Standardize code files and align database SQL queries beautifully.",
    icon: "Terminal",
    category: "Developer",
    usageCount: 65100,
  },
  {
    id: "markdown-preview",
    name: "Live Markdown Editor Preview",
    description: "Write raw markdown styling on the fly and view dynamic formatted previews immediately.",
    icon: "FileText",
    category: "Developer",
    usageCount: 38200,
  },
  {
    id: "base64-converter",
    name: "Base64 Encoder & Decoder",
    description: "Encode raw data into safe Base64 formatting or decode scrambled strings instantly.",
    icon: "Binary",
    category: "Developer",
    usageCount: 54100,
  },
  {
    id: "url-encoder-decoder",
    name: "URL Param Encoder / Decoder",
    description: "Encode illegal characters for query requests or unpack complex URL query chains.",
    icon: "Link",
    category: "Developer",
    usageCount: 36200,
  },
  {
    id: "jwt-decoder",
    name: "JWT Authentication Decoder",
    description: "Decode corporate JSON Web Tokens safely to inspect payload objects and signing dates.",
    icon: "BadgeCheck",
    category: "Developer",
    usageCount: 49500,
    new: true,
  },
  {
    id: "uuid-generator",
    name: "RFC 4122 UUID v4 Generator",
    description: "Generate list arrays of cryptographically unique, random v4 UUID identifiers.",
    icon: "Workflow",
    category: "Developer",
    usageCount: 41200,
  },
  {
    id: "regex-tester",
    name: "Interactive Regular Expression Tester",
    description: "Write custom regular expressions, test string inputs, and highlight search match results.",
    icon: "SpellCheck",
    category: "Developer",
    usageCount: 53100,
  },
  {
    id: "timestamp-converter",
    name: "Epoch Unix Timestamp Converter",
    description: "Convert seconds or milliseconds timestamps into human calendar dates and vice-versa.",
    icon: "Clock",
    category: "Developer",
    usageCount: 48900,
  },
  {
    id: "color-picker",
    name: "Aesthetic Color & Gradient Mixer",
    description: "Pick colors, generate smooth CSS gradients, extract hex/rgb models, and copy styling.",
    icon: "Palette",
    category: "Developer",
    usageCount: 69400,
  },
  {
    id: "api-tester",
    name: "Sleek REST API Request Tester",
    description: "Send mock GET, POST, or PUT fetch calls to custom URL servers to inspect response objects.",
    icon: "Terminal",
    category: "Developer",
    usageCount: 39500,
  },

  // 12. SECURITY CATEGORY
  {
    id: "password-strength",
    name: "Secure Password Strength Grader",
    description: "Analyze strength entropy, check dictionary attacks, and grade safety speed thresholds.",
    icon: "ShieldAlert",
    category: "Security",
    usageCount: 58200,
  },
  {
    id: "hash-generator",
    name: "MD5 & SHA-256 Checksum Engine",
    description: "Compute robust standard cryptographic SHA-256, SHA-512, or MD5 checksums of plain strings.",
    icon: "Fingerprint",
    category: "Security",
    usageCount: 48900,
  },
  {
    id: "aes-crypt",
    name: "Symmetric AES Encryption Utility",
    description: "Encrypt message texts with dynamic passwords or decrypt secure base64 secret envelopes.",
    icon: "Lock",
    category: "Security",
    usageCount: 39100,
    new: true,
  },
  {
    id: "random-token",
    name: "Entropy Security Token Spawner",
    description: "Generate highly secure random salt keys, hex phrases, or numeric authorization tokens.",
    icon: "Workflow",
    category: "Security",
    usageCount: 31200,
  },
  {
    id: "secure-password-checker",
    name: "Corporate Password Safety Audit",
    description: "Audit password safety policies, search common lists, and read secure credential directives.",
    icon: "ShieldCheck",
    category: "Security",
    usageCount: 29500,
  },

  // 13. CALCULATOR CATEGORY
  {
    id: "calculator-basic",
    name: "Modern Floating Calculator",
    description: "Quick clean client-side floating standard calculator for math equations.",
    icon: "Calculator",
    category: "Calculator",
    usageCount: 84300,
  },
  {
    id: "calculator-scientific",
    name: "Scientific Formula Calculator",
    description: "Solve complex algebraic equations, log bases, sines, cosines, tangents, and exponent grids.",
    icon: "Dna",
    category: "Calculator",
    usageCount: 43200,
  },
  {
    id: "calculator-percentage",
    name: "Percentage Increase & Fractional Tool",
    description: "Determine percentage gaps, ratio discounts, compounding interests, or relative shares.",
    icon: "Percent",
    category: "Calculator",
    usageCount: 31200,
  },
  {
    id: "calculator-age",
    name: "Precision Lifespan Age Calculator",
    description: "Find total years, months, weeks, days, and seconds since your birth or key milestones.",
    icon: "Clock",
    category: "Calculator",
    usageCount: 22400,
  },
  {
    id: "calculator-bmi",
    name: "Healthy BMI Zone Calculator",
    description: "Assess physical body mass index grids based on imperial or metric ratios with active indicators.",
    icon: "Activity",
    category: "Calculator",
    usageCount: 29500,
  },
  {
    id: "calculator-loan",
    name: "EMI Loan & Mortgage Planner",
    description: "Visualize compounding interest schedules, monthly repayments, and full loan amortization scales.",
    icon: "Calculator",
    category: "Calculator",
    usageCount: 38200,
  },
  {
    id: "calculator-currency",
    name: "Sleek Real-time Currency Converter",
    description: "Check visual live-updating foreign currency conversions for CAD, EUR, USD, JPY, and GBP.",
    icon: "Workflow",
    category: "Calculator",
    usageCount: 51200,
    new: true,
  },
  {
    id: "calculator-unit-converter",
    name: "Aesthetic Multi-Unit Converter",
    description: "Swap and scale length metrics, weights, heat temperatures, or standard computer times instantly.",
    icon: "Maximize2",
    category: "Calculator",
    usageCount: 68900,
  }
];

export const PRICING_PLANS = [
  {
    name: "Free",
    priceMonthly: 0,
    priceYearly: 0,
    description: "Essential utility tools for casual searchers.",
    features: [
      "Access to all 60+ standard tools",
      "Limited Gemini-powered credits (10 daily)",
      "Temporary mailbox (automatically cleaned up)",
      "Standard client-only url redirection",
      "Basic local history storage",
      "Contains clean visual ads",
    ],
    buttonText: "Current Plan",
    pro: false,
  },
  {
    name: "Pro",
    priceMonthly: 9,
    priceYearly: 79,
    description: "For professionals, students, and active creators.",
    features: [
      "Ad-free premium SaaS interface",
      "Unlimited Gemini-powered credits",
      "Permanent & customizable temporary email domains",
      "Larger simulated cloud file storage (10 GB)",
      "Permanent URL shortening redirects (never expire)",
      "Bulk batch processing for PDF and images",
      "Priority API Key generation & direct code access",
    ],
    buttonText: "Upgrade to Pro",
    pro: true,
    popular: true,
  },
  {
    name: "Team",
    priceMonthly: 29,
    priceYearly: 249,
    description: "Collaborative workspaces for groups & offices.",
    features: [
      "Everything in Pro plan included",
      "Shared secure team workspace panel",
      "Multi-user folder organization and editing",
      "Centralized billing & usage metrics",
      "Dedicated high-speed cloud file server access",
      "Up to 10 active team members",
    ],
    buttonText: "Deploy Workspace",
    pro: true,
  },
  {
    name: "Enterprise",
    priceMonthly: 99,
    priceYearly: 899,
    description: "For high-volume APIs and white-label tools.",
    features: [
      "Unlimited system API integrations",
      "Custom brand white-labeling option",
      "Dedicated premium server resource & 99.9% SLA",
      "SAML / SSO single sign-on security controls",
      "24/7 Priority support manager",
    ],
    buttonText: "Contact Sales",
    pro: true,
  }
];

export const TESTIMONIALS = [
  {
    id: "t1",
    name: "Alex Rivera",
    role: "Full-Stack Software Engineer",
    text: "All Tools has replaced at least 6 separate websites I used to visit daily. The JSON Formatter and Base64 tools are extremely sleek, and the fact that I can generate a temp email directly inside the same window is fantastic. Saving this as my home tab!",
    rating: 5,
    avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80",
  },
  {
    id: "t2",
    name: "Sarah Jenkins",
    role: "Freelance Content Strategist",
    text: "The AI Content Writer operates beautifully. It helps me create fast drafts for social media and client summaries. The pricing is unbeatable compared to standalone single-use AI tools. High-contrast typography and speed are phenomenal.",
    rating: 5,
    avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80",
  },
  {
    id: "t3",
    name: "Kenji Takahashi",
    role: "Creative UI Designer",
    text: "A masterclass in SaaS tool design. The dark mode with glassmorphic accents feels so premium. Client-side image resizing is super responsive and didn't crash my mobile browser once. Excellent mobile responsiveness!",
    rating: 5,
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80",
  }
];

export const FAQS = [
  {
    question: "How secure is All Tools for my files?",
    answer: "Extremely secure. All processing tools like the Image Resizer, JSON Formatter, and Developer utilities operate completely client-side. For file uploads and cloud storage, files are securely cached in-memory/simulated space with automated cleanups and password-protection options."
  },
  {
    question: "Do the temporary email boxes support attachments?",
    answer: "Yes! Our mock mailbox system simulates receiving fully custom automated messages, verification codes, and security alerts. Perfect for testing your onboarding emails or workflows safely without spamming your primary accounts."
  },
  {
    question: "How does the native URL shortener work?",
    answer: "Unlike other mock systems, our URL shortener registers real redirection routes (`/r/:code`) directly in our Express backend. When you send someone that link, our server performs a true HTTP 302 redirect to your original target. Try it out!"
  },
  {
    question: "Can I use my custom OpenAI or Gemini API keys?",
    answer: "Our Pro and Enterprise accounts gain access to custom API Key management directly in the user profile dashboard. This allows you to generate API keys or hook up your custom endpoints with priority server speeds and unlimited quota."
  }
];
